version: '3.9'
services:
  keycloak:
    container_name: beercloak
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 18080:8080
    - 443:8443
    environment:
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME: id.keycloak.test
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /opt/keycloak/imports/beer-realm.json
    command: start
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./cert.pem:/etc/x509/https/tls.crt
    - ./cert-key.pem:/etc/x509/https/tls.key
    - "./test/beer-realm.json:/opt/keycloak/imports/beer-realm.json"
    networks:
    - beernet

  maildev:
    container_name: maildev
    image: maildev/maildev:1.1.0
    ports:
    - "1080:80"
    - "1234:25"
    networks:
    - beernet

networks:
  beernet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
